---
project_code: pub-dspace
profile: cdl-pad-dev
region: us-west-2

constants:
  vpc_id: vpc-04d70b61
  domain: escholarship.org

stack_defaults:
  timeout_in_minutes: 10
  on_failure: DO_NOTHING # handy for debugging
