---

template:
  path: cluster.yaml

parameters:
  project_code: {{stack_group_config.project_code}}
  ClusterName: !join
    - {{stack_group_config.project_code}}
    - "-dev-cluster"
  ProgramTag: pub
  ServiceTag: dspace
  EnvironmentTag: dev
