---

template:
  path: requirements.yaml.j2

parameters:
  ClusterName: !join ['', [{{stack_group_config.project_code}}, '-dev-cluster']]
  ProgramTag: pub
  ServiceTag: dspace
  EnvironmentTag: !join ['', [{{stack_group_config.project_code}}]]
